// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZe8QOVpCnGtVw2sUWZfBCAZtpbgBTnrw',
    appId: '1:594898263149:web:f4f2765f1305ef3bbe7364',
    messagingSenderId: '594898263149',
    projectId: 'cyphlab-expense-tracker-7f83c',
    authDomain: 'cyphlab-expense-tracker-7f83c.firebaseapp.com',
    storageBucket: 'cyphlab-expense-tracker-7f83c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWGUwpBFwKcw4uRdvOEEJUtmkPK7FlsA8',
    appId: '1:594898263149:android:4b1c8c693dcf479fbe7364',
    messagingSenderId: '594898263149',
    projectId: 'cyphlab-expense-tracker-7f83c',
    storageBucket: 'cyphlab-expense-tracker-7f83c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWczd9zZUhEB2mHsys9tVVmz-fSzo3B1M',
    appId: '1:594898263149:ios:9f231e33cb827018be7364',
    messagingSenderId: '594898263149',
    projectId: 'cyphlab-expense-tracker-7f83c',
    storageBucket: 'cyphlab-expense-tracker-7f83c.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWczd9zZUhEB2mHsys9tVVmz-fSzo3B1M',
    appId: '1:594898263149:ios:9f231e33cb827018be7364',
    messagingSenderId: '594898263149',
    projectId: 'cyphlab-expense-tracker-7f83c',
    storageBucket: 'cyphlab-expense-tracker-7f83c.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZe8QOVpCnGtVw2sUWZfBCAZtpbgBTnrw',
    appId: '1:594898263149:web:dd8d189bc856c468be7364',
    messagingSenderId: '594898263149',
    projectId: 'cyphlab-expense-tracker-7f83c',
    authDomain: 'cyphlab-expense-tracker-7f83c.firebaseapp.com',
    storageBucket: 'cyphlab-expense-tracker-7f83c.firebasestorage.app',
  );
}
